here::i_am("target-data/get_target_data_time_series_hubverse.R")
library(cli)
suppressPackageStartupMessages(library(dplyr))
library(readr)
library(tidyr)

options(readr.show_col_types = FALSE)

#' @description
#' `get_location_data` returns supplemental information about locations used in
#' the FluSight Forecast hub.
#'
#' @returns A dataframe with four columns: abbreviation (two-letter state code),
#' location (FIPS code), location_name (state name), and population.
get_location_data <- function() {
  location_file <-
    read_csv(file = "https://raw.githubusercontent.com/cdcepi/FluSight-forecast-hub/main/auxiliary-data/locations.csv") # nolint: line_length_linter.
  # first 4 columns of locations.csv are abbreviation, location, location_name, population
  location_file %>% dplyr::select(1:4)
}

#' @description
#' `get_base_target_data` returns weekly target data generated by the FluSight
#' FluSight Forecast hub.
#'
#' @param as_of Optional "YYYY-MM-DD" string. If provided, read archived target data instead of the latest version.
#' @returns A dataframe
get_base_target_data <- function(as_of = NULL) {
  if (!is.null(as_of)) {
    tryCatch(
      as.Date(as_of, format = "%Y-%m-%d"),
      error = function(e) stop(paste0("Invalid date format. Please use 'YYYY-MM-DD': ", as_of))
    )
    browser()
    file_name <- file.path(
      here::here(),
      paste0("auxiliary-data/target-data-archive/target-hospital-admissions_", as_of, ".csv"))
  } else {
    file_name <- file.path(here::here(), "target-data/target-hospital-admissions.csv")
  }

  cli::cli_inform(paste0("Reading target data from ", file_name, "..."))

  base_target_data <- readr::read_csv(file = file_name)
  latest_date <- max(base_target_data$date, na.rm = TRUE)

  if (!is.null(as_of) && as.Date(latest_date) != as.Date(as_of)) {
    cli::cli_alert_danger(
      paste0("Latest date in the target data (", latest_date, ") does not match the 'as_of' date (", as_of, ").")
    )
    stop()
  }

  cbind(
    base_target_data,
    data.frame(as_of = as.Date(latest_date))
  )
}

#' @description
#' `create_time_series_wk_inc` creates Hubverse-formatted oracle output
#' target data for the "wk inc flu hosp" target.
#'
#' @param weekly_data Dataframe with weekly target data generated by the hub.
#' @param location_date Dataframe with information about each state.
#' @param after "YYYY-MM_DD" string. Base target data dated on or earlier will be excluded.
#' @returns A dataframe
create_time_series_target_data <- function(weekly_data, location_data, after = "2024-11-01") {
  filter_date <- tryCatch(
    as.Date(after, format = "%Y-%m-%d"),
    error = function(e) stop("Invalid date format. Please use 'YYYY-MM-DD'.")
  )

  filtered_weekly_data <- weekly_data %>%
  dplyr::filter(date >= filter_date) %>%
      dplyr::select(-location) %>%
      dplyr::inner_join(location_data,
                        by = c("location_name"))
  time_series_wk_inc <- cbind(
    data.frame(target = "wk inc flu hosp"),
    filtered_weekly_data[c("date", "location", "value", "weekly_rate", "as_of")]
  )
  colnames(time_series_wk_inc) <- c("target", "target_end_date", "location", "observation", "weekly_rate", "as_of")

  time_series_wk_inc
}

test_time_series_output <- function() {
  # create a vector to store test results
  ok <- (TRUE)
  ok
}

# Run tests
ok <- test_time_series_output()
ok <- ifelse(is.logical(ok), ok, FALSE)
if (isTRUE(all(ok))) {
  cli::cli_alert_success("All time series tests passed.")
} else {
  cli::cli_alert_danger("Time series tests failed: exiting script.")
  quit(save = "no", status = 1)
}

# Create time series target data
location_data <- get_location_data()
weekly_data_all <- get_base_target_data(as_of="2025-01-11")
time_series_target <- create_time_series_target_data(weekly_data_all, location_data)

as_of <- time_series_target$as_of[1]
time_series_path <- file.path(here::here(), paste0("target-data/time_series/as_of=", as_of))
if (!dir.exists(time_series_path)) {
  dir.create(time_series_path, recursive = TRUE)
}
tryCatch(
  write.csv(time_series_target, file = paste0(time_series_path, "/time-series.csv"), row.names = FALSE),
  error = function(e) {
    cli::cli_alert_danger(paste0(
                                 "Failed when writing time series target data to ",
                                 time_series_path,
                                 "/time-series.csv:",
                                 e$message))
    quit(save = "no", status = 1)
  }
)
cli::cli_alert_success(paste0("Time series target data written to ", time_series_path, "/time-series.csv."))
